name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
#   deploy:
#     runs-on: ubuntu-latest

#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}

#     needs: build

#     steps:
#       - name: Deploy to GitHub Pages
#         run: |
#           npm run deploy
